### ISSUE TITLE
Quick Fix: code in blog post doesn't compile

### ISSUE THREAD

**Issue by AviFS** [Freshman-tech/news-demo#1]
**It's not anywhere near as bad as it sounds. The code in this repo works great, the blog post is just slightly out of sync. Quick fix below!**

## Problem
This is specifically for checkpoint 2. In the [blog post](https://freshman.tech/web-development-with-go/) at checkpoint two, it shows `main.go` with the following line:

```go
newsapi := news.NewClient(apiKey, 20)
```

But this doesn't compile; it gives a type mismatch:

```
IN: news.NewClient
 have (string, number)
 want (*http.Client, string, int)
```

## Solution

Luckily, the code in the repo at [checkpoint 2](https://github.com/Freshman-tech/news-demo/tree/master/checkpoints/02) works just great, it's just slightly different. The solution is to use this code in the blog post instead!

```go
myClient := &http.Client{Timeout: 10 * time.Second}
newsapi := news.NewClient(myClient, apiKey, 20)
```

**Comment by AviFS** [comment]
Specifically:

There are three codeblocks between this:
> Return to your main.go file, retrieve the News API key from the environment, and create a new Client instance as shown below...

and this

> The searchHandler function has been changed. It now accepts a pointer to news.Client and returns an anonymous function which satisfies the http.HandlerFunc type.

---

In the first codeblock, the two lines appear correctly. But in the other two codeblocks that follow, it's shown simply as `newsapi := news.NewClient(apiKey, 20)`

**Comment by ayoisaiah** [comment]
Thanks a lot for catching this issue, and for the detailed explanation. I have updated the article so it's fixed now!

**Comment by AviFS** [comment]
That was really fast! The tabbing looks off in the two codeblocks you fixed, though. Looks like the two lines should be indented one more level. Thanks for being so responsive!

<img width="631" alt="Screen Shot 2021-08-23 at 2 26 19 PM" src="https://user-images.githubusercontent.com/58723244/130521761-e085fe34-0537-479e-a560-d16fdd29e1d3.png">

<img width="621" alt="Screen Shot 2021-08-23 at 2 26 27 PM" src="https://user-images.githubusercontent.com/58723244/130521746-1c45fdc4-84f1-4d37-ada7-1888f5645c95.png">

**Comment by ayoisaiah** [comment]
Thanks once again, I was deceived by my editor....it converted tabs to spaces. Should be fixed now!

**Comment by AviFS** [comment]
Always those pesky tabs & spaces! Thanks for the great intro article, Isaiah
